config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "prototypes#index"
  resources :prototypes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  validates :profile, presence: true
  validates :occupation, presence: true
  validates :position, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:profile,:occupation,:position])
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prototypes_helper.rb
module PrototypesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ProtoSpace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <%# ログインしているときは以下を表示するようにしましょう %>
          <% if user_signed_in? %>
             <div class="nav__right"> 
              <%= link_to "ログアウト", destroy_user_session_path, class: :nav__logout, method: :delete %>
              <%= link_to "New Proto", new_prototype_path, class: :nav__btn %>
             </div>
             <% else %>
          <%# // ログインしているときは上記を表示するようにしましょう %>
          <%# ログインしていないときは以下を表示するようにしましょう %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
            <% end %>
          <%# // ログインしていないときは上記を表示するようにしましょう %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © PROTO SPACE All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/prototypes/_form.html.erb
<%= form_with local: true do |f|%>
  <div class="field">
    <%= f.label :hoge, "プロトタイプの名称" %><br />
    <%= f.text_field :hoge %>
  </div>

  <div class="field">
    <%= f.label :hoge, "キャッチコピー" %><br />
    <%= f.text_area :hoge, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :hoge, "コンセプト" %><br />
    <%= f.text_area :hoge, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :hoge, "プロトタイプの画像" %><br />
    <%= f.file_field :hoge %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/prototypes/_prototype.html.erb
<div class="card">
  <%= link_to image_tag("プロトタイプの画像", class: :card__img ), root_path%>
  <div class="card__body">
    <%= link_to "プロトタイプのタイトル", root_path, class: :card__title%>
    <p class="card__summary">
      <%= "プロトタイプのキャッチコピー" %>
    </p>
    <%= link_to "by プロトタイプの投稿者名", root_path, class: :card__user %>
  </div>
</div>

app/views/prototypes/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">プロトタイプ編集</h2>
      <%# 部分テンプレートでフォームを表示する %>
    </div>
  </div>
</div>

app/views/prototypes/index.html.erb
<main class="main">
  <div class="inner">
    <%# ログインしているときは以下を表示する %>
    <% if user_signed_in? %>
      <div class="greeting"> 
        こんにちは、
         <%= link_to "#{current_user.name}さん", root_path, class: :greeting__link %>
      </div> 
      <% end %>
    <%# // ログインしているときは上記を表示する %>
    <div class="card__wrapper">
      <%# 投稿機能実装後、部分テンプレートでプロトタイプ投稿一覧を表示する %>
    </div>
  </div>
</main>

app/views/prototypes/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規プロトタイプ投稿</h2>
        <%# 部分テンプレートでフォームを表示する %>
    </div>
  </div>
</div>

app/views/prototypes/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= "プロトタイプのタイトル"%>
      </p>
      <%= link_to "by プロトタイプの投稿者", root_path, class: :prototype__user %>
      <%# プロトタイプの投稿者とログインしているユーザーが同じであれば以下を表示する %>
        <div class="prototype__manage">
          <%= link_to "編集する", root_path, class: :prototype__btn %>
          <%= link_to "削除する", root_path, class: :prototype__btn %>
        </div>
      <%# // プロトタイプの投稿者とログインしているユーザーが同じであれば上記を表示する %>
      <div class="prototype__image">
        <%= image_tag "プロトタイプの画像" %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">キャッチコピー</p>
          <p class="detail__message">
            <%= "プロトタイプのキャッチコピー" %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">コンセプト</p>
          <p class="detail__message">
            <%= "プロトタイプのコンセプト" %>
          </p>
        </div>
      </div>
      <div class="prototype__comments">
        <%# ログインしているユーザーには以下のコメント投稿フォームを表示する %>
          <%# <%= form_with local: true do |f|%>
            <div class="field">
              <%# <%= f.label :hoge, "コメント" %><br />
              <%# <%= f.text_field :hoge %>
            </div>
            <div class="actions">
              <%# <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <%# <% end %> 
        <%# // ログインしているユーザーには上記を表示する %>
        <ul class="comments_lists">
          <%# 投稿に紐づくコメントを一覧する処理を記述する %>
            <li class="comments_list">
              <%# <%= " コメントのテキスト "%>
              <%# <%= link_to "（ ユーザー名 ）", root_path, class: :comment_user %>
            </li>
          <%# // 投稿に紐づくコメントを一覧する処理を記述する %>
        </ul>
      </div>
    </div>
  </div>
</main>